CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY, test TEXT NOT NULL, player TEXT NOT NULL, belief TEXT NOT NULL,
  name TEXT, created INTEGER NOT NULL, deck TEXT, calls TEXT NOT NULL DEFAULT '',
  targets TEXT NOT NULL DEFAULT '', n INTEGER NOT NULL DEFAULT 0, hits INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS tally (
  test TEXT, player TEXT, belief TEXT, trials INTEGER NOT NULL DEFAULT 0, hits INTEGER NOT NULL DEFAULT 0,
  runs INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (test, player, belief));
CREATE TABLE IF NOT EXISTS pos (
  test TEXT, pos INTEGER, trials INTEGER NOT NULL DEFAULT 0, hits INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (test, pos));
CREATE TABLE IF NOT EXISTS forecast (
  day TEXT NOT NULL, name TEXT NOT NULL, player TEXT NOT NULL, belief TEXT NOT NULL,
  calls TEXT NOT NULL, created INTEGER NOT NULL, PRIMARY KEY (day, name));
CREATE TABLE IF NOT EXISTS draws (day TEXT PRIMARY KEY, round INTEGER NOT NULL, randomness TEXT NOT NULL, target TEXT NOT NULL);
